apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    app: service
spec:
  ports:
    - port: 3306
  selector:
    app: service
    tier: mysql
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  labels:
    app: service
spec:
  selector:
    matchLabels:
      app: service
      tier: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: service
        tier: mysql
    spec:
      containers:
      - image: mysql:5.6
        name: mysql
        env:
        - name: MYSQL_DATABASE
          value: sample
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-pass-xxxx
              key: password
        - name: MYSQL_USER
          value: sample
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-pass-xxxx
              key: password
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim
